-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_logs
(
    log_id serial NOT NULL,
    user_id integer,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    record_id integer,
    old_value jsonb,
    new_value jsonb,
    ip_address character varying(45) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.kader
(
    kader_id integer NOT NULL DEFAULT nextval('komunitas_komunitas_id_seq'::regclass),
    opd_id integer NOT NULL,
    nama_kader character varying(100) COLLATE pg_catalog."default" NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    CONSTRAINT komunitas_pkey PRIMARY KEY (kader_id)
);

ALTER TABLE IF EXISTS public.kader
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.opd
(
    opd_id serial NOT NULL,
    nama_opd character varying(100) COLLATE pg_catalog."default" NOT NULL,
    alamat text COLLATE pg_catalog."default",
    kontak character varying(50) COLLATE pg_catalog."default",
    pic character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    nik_pic character varying(16) COLLATE pg_catalog."default",
    CONSTRAINT opd_pkey PRIMARY KEY (opd_id)
);

ALTER TABLE IF EXISTS public.opd
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pengajuan_perubahan_data
(
    pengajuan_id serial NOT NULL,
    relawan_id integer NOT NULL,
    jenis_perubahan character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_lama jsonb,
    data_baru jsonb NOT NULL,
    status status_pengajuan DEFAULT 'Menunggu Review'::status_pengajuan,
    catatan_relawan text COLLATE pg_catalog."default",
    catatan_verifikator text COLLATE pg_catalog."default",
    tanggal_pengajuan timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    tanggal_verifikasi timestamp with time zone,
    verifikator_id integer,
    CONSTRAINT pengajuan_perubahan_data_pkey PRIMARY KEY (pengajuan_id)
);

ALTER TABLE IF EXISTS public.pengajuan_perubahan_data
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pengelola_opd
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    opd_id integer NOT NULL,
    CONSTRAINT pengelola_opd_pkey PRIMARY KEY (id),
    CONSTRAINT pengelola_opd_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.penugasan_relawan
(
    penugasan_id serial NOT NULL,
    relawan_id integer NOT NULL,
    opd_id integer NOT NULL,
    kader_id integer,
    sk_id integer,
    jabatan character varying(100) COLLATE pg_catalog."default",
    status_keaktifan status_keaktifan DEFAULT 'Aktif'::status_keaktifan,
    nomor_sk_manual character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    penugasan character varying(100) COLLATE pg_catalog."default",
    detail_jabatan character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT penugasan_relawan_pkey PRIMARY KEY (penugasan_id)
);

ALTER TABLE IF EXISTS public.penugasan_relawan
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pic_kader
(
    pic_kader_id serial NOT NULL,
    relawan_id integer NOT NULL,
    kader_id integer NOT NULL,
    tanggal_mulai date DEFAULT CURRENT_DATE,
    tanggal_selesai date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Aktif'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pic_kader_pkey PRIMARY KEY (pic_kader_id)
);

ALTER TABLE IF EXISTS public.pic_kader
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.relawan
(
    relawan_id serial NOT NULL,
    user_id integer NOT NULL,
    jenis_kelamin jenis_kelamin NOT NULL,
    tempat_lahir character varying(50) COLLATE pg_catalog."default",
    tanggal_lahir date,
    alamat_ktp text COLLATE pg_catalog."default" NOT NULL,
    kelurahan character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT relawan_pkey PRIMARY KEY (relawan_id),
    CONSTRAINT relawan_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.relawan
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.saran_masukan
(
    saran_id serial NOT NULL,
    user_id integer NOT NULL,
    subjek character varying(255) COLLATE pg_catalog."default",
    pesan text COLLATE pg_catalog."default" NOT NULL,
    status status_saran DEFAULT 'Menunggu'::status_saran,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    catatan_admin text COLLATE pg_catalog."default",
    CONSTRAINT saran_masukan_pkey PRIMARY KEY (saran_id)
);

CREATE TABLE IF NOT EXISTS public.surat_keputusan
(
    sk_id serial NOT NULL,
    nomor_sk character varying(100) COLLATE pg_catalog."default" NOT NULL,
    judul_sk character varying(255) COLLATE pg_catalog."default",
    tanggal_terbit date,
    opd_id integer NOT NULL,
    file_path text COLLATE pg_catalog."default" NOT NULL,
    status status_keaktifan DEFAULT 'Aktif'::status_keaktifan,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    batas_aktif date,
    CONSTRAINT surat_keputusan_pkey PRIMARY KEY (sk_id),
    CONSTRAINT surat_keputusan_nomor_sk_key UNIQUE (nomor_sk)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    nik character varying(16) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role user_role NOT NULL,
    nama_lengkap character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    no_hp character varying(15) COLLATE pg_catalog."default",
    foto_profil text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_nik_key UNIQUE (nik)
);

ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.kader
    ADD CONSTRAINT fk_komunitas_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_komunitas_opd
    ON public.kader(opd_id);


ALTER TABLE IF EXISTS public.pengajuan_perubahan_data
    ADD CONSTRAINT fk_pengajuan_relawan FOREIGN KEY (relawan_id)
    REFERENCES public.relawan (relawan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pengajuan_perubahan_data
    ADD CONSTRAINT fk_pengajuan_verifikator FOREIGN KEY (verifikator_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pengelola_opd
    ADD CONSTRAINT fk_pengelola_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pengelola_opd
    ADD CONSTRAINT fk_pengelola_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pengelola_opd_user_id_key
    ON public.pengelola_opd(user_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_komunitas FOREIGN KEY (kader_id)
    REFERENCES public.kader (kader_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_penugasan_komunitas
    ON public.penugasan_relawan(kader_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_penugasan_opd
    ON public.penugasan_relawan(opd_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_relawan FOREIGN KEY (relawan_id)
    REFERENCES public.relawan (relawan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_penugasan_relawan
    ON public.penugasan_relawan(relawan_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_sk FOREIGN KEY (sk_id)
    REFERENCES public.surat_keputusan (sk_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pic_kader
    ADD CONSTRAINT fk_pic_kader FOREIGN KEY (kader_id)
    REFERENCES public.kader (kader_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS unique_active_pic_per_kader
    ON public.pic_kader(kader_id);


ALTER TABLE IF EXISTS public.pic_kader
    ADD CONSTRAINT fk_pic_relawan FOREIGN KEY (relawan_id)
    REFERENCES public.relawan (relawan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.relawan
    ADD CONSTRAINT fk_relawan_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS relawan_user_id_key
    ON public.relawan(user_id);


ALTER TABLE IF EXISTS public.saran_masukan
    ADD CONSTRAINT fk_saran_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.surat_keputusan
    ADD CONSTRAINT fk_sk_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;

-- Tambahan: Definisi Tipe Data ENUM (tidak terekspor otomatis)
CREATE TYPE public.jabatan AS ENUM ('Ketua','Wakil','Sekretaris','Bendahara','Seksi','Anggota');
CREATE TYPE public.jenis_kelamin AS ENUM ('L', 'P');
CREATE TYPE public.status_keaktifan AS ENUM ('Aktif', 'Tidak Aktif', 'Cuti');
CREATE TYPE public.status_kegiatan AS ENUM ('Berjalan', 'Selesai', 'Ditunda', 'Dibatalkan');
CREATE TYPE public.status_pengajuan AS ENUM ('Menunggu Review', 'Diterima', 'Ditolak');
CREATE TYPE public.status_saran AS ENUM ('Menunggu', 'Selesai');
CREATE TYPE public.user_role AS ENUM ('super_admin', 'opd', 'relawan');

-- 1. Mengaktifkan RLS pada tabel-tabel penting
ALTER TABLE public.opd ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relawan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kegiatan_relawan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengajuan_perubahan_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penugasan_relawan ENABLE ROW LEVEL SECURITY;

-- 2. Menghapus policy lama jika ada (agar script ini aman dijalankan berulang kali)
DROP POLICY IF EXISTS super_admin_all_opd ON public.opd;
DROP POLICY IF EXISTS opd_relawan_select_opd ON public.opd;

DROP POLICY IF EXISTS super_admin_all_relawan ON public.relawan;
DROP POLICY IF EXISTS self_access_relawan ON public.relawan;

DROP POLICY IF EXISTS super_admin_all_penugasan ON public.penugasan_relawan;
DROP POLICY IF EXISTS self_access_penugasan ON public.penugasan_relawan;


-- ==========================================
-- 3. MEMBUAT POLICIES UNTUK TABEL: opd
-- ==========================================
-- [Super Admin]: Bebas melakukan CRUD ke tabel OPD
CREATE POLICY super_admin_all_opd ON public.opd 
    FOR ALL 
    USING (current_setting('app.current_user_role', true) = 'super_admin');

-- [OPD & Relawan]: Hanya boleh melihat (SELECT) tabel OPD, tidak boleh mengedit/menghapus
CREATE POLICY opd_relawan_select_opd ON public.opd
    FOR SELECT 
    USING (current_setting('app.current_user_role', true) IN ('opd', 'relawan'));


-- ==========================================
-- 4. MEMBUAT POLICIES UNTUK TABEL: relawan
-- ==========================================
-- [Super Admin]: Bebas melakukan CRUD ke tabel relawan
CREATE POLICY super_admin_all_relawan ON public.relawan 
    FOR ALL 
    USING (current_setting('app.current_user_role', true) = 'super_admin');

-- [Relawan]: Hanya boleh melihat & mengedit profil aslinya sendiri (user_id miliknya)
CREATE POLICY self_access_relawan ON public.relawan
    FOR ALL
    USING (user_id = current_setting('app.current_user_id', true)::integer);


-- ==========================================
-- 5. MEMBUAT POLICIES UNTUK TABEL: penugasan_relawan
-- ==========================================
-- [Super Admin]: Bebas akses
CREATE POLICY super_admin_all_penugasan ON public.penugasan_relawan 
    FOR ALL 
    USING (current_setting('app.current_user_role', true) = 'super_admin');

-- [Relawan]: Hanya boleh melihat (SELECT) penugasannya sendiri
CREATE POLICY self_access_penugasan ON public.penugasan_relawan
    FOR SELECT
    USING (relawan_id IN (
        SELECT relawan_id FROM public.relawan WHERE user_id = current_setting('app.current_user_id', true)::integer
    ));


-- ==========================================
-- CATATAN PENTING UNTUK QUERY BACKEND EXPRESS.JS
-- ==========================================
-- Mulai sekarang, setiap kali Node.js ingin melakukan query ke database, 
-- Node.js WAJIB mengirimkan context user terlebih dahulu. Contoh di kode Controller:
-- 
-- await pool.query("SET LOCAL app.current_user_id = $1;", [req.user.user_id]);
-- await pool.query("SET LOCAL app.current_user_role = $1;", [req.user.role]);
-- const result = await pool.query("SELECT * FROM opd");
--
-- RLS ini tidak mempengaruhi query yang dilakukan menggunakan user SUPERUSER postgres 
-- jika Role 'postgres' di-set dengan opsi BYPASSRLS.
-- Jika kamu memakai user 'postgres' di .env yang punya privileges Superuser, 
-- kamu perlu menggunakan perintah ALTER ROLE postgres NOSUPERUSER NOBYPASSRLS agar RLS bekerja,
-- atau buat user database baru seperti 'app_user' untuk backend kamu.
-- ==========================================
-- FIX RLS UNTUK TABEL: kader
-- ==========================================

-- 1. Aktifkan RLS pada tabel kader
ALTER TABLE public.kader ENABLE ROW LEVEL SECURITY;

-- 2. Hapus policy lama jika ada
DROP POLICY IF EXISTS super_admin_all_kader ON public.kader;
DROP POLICY IF EXISTS opd_access_kader ON public.kader;
DROP POLICY IF EXISTS relawan_access_kader ON public.kader;

-- 3. [Super Admin]: Bebas melakukan CRUD
CREATE POLICY super_admin_all_kader ON public.kader 
    FOR ALL 
    USING (current_setting('app.current_user_role', true) = 'super_admin');

-- 4. [OPD]: Hanya boleh akses kader dari OPD mereka sendiri
CREATE POLICY opd_access_kader ON public.kader 
    FOR ALL 
    USING (
        current_setting('app.current_user_role', true) = 'opd' 
        AND opd_id = current_setting('app.current_opd_id', true)::integer
    );

-- 5. [Relawan]: Hanya boleh SELECT kader dari OPD mereka
CREATE POLICY relawan_access_kader ON public.kader 
    FOR SELECT 
    USING (
        current_setting('app.current_user_role', true) = 'relawan'
        AND opd_id IN (
            SELECT pr.opd_id 
            FROM public.penugasan_relawan pr 
            JOIN public.relawan r ON pr.relawan_id = r.relawan_id 
            WHERE r.user_id = current_setting('app.current_user_id', true)::integer
        )
    );

Membuatt aturan relawan dapat melihat data relawn di user mereka sendiri
CREATE POLICY relawan_self_select ON relawan
    FOR SELECT USING (true);  -- atau lebih ketat: user_id = current_user_id



-- Update RLS TERBARU
DROP POLICY IF EXISTS super_admin_all_pengajuan ON public.pengajuan_perubahan_data;
DROP POLICY IF EXISTS relawan_own_pengajuan ON public.pengajuan_perubahan_data;
DROP POLICY IF EXISTS opd_all_pengajuan ON public.pengajuan_perubahan_data;

-- Super Admin: full access
CREATE POLICY super_admin_all_pengajuan ON public.pengajuan_perubahan_data
    FOR ALL
    USING (current_setting('app.current_user_role', true) = 'super_admin');

-- OPD: bisa lihat dan update semua pengajuan
CREATE POLICY opd_all_pengajuan ON public.pengajuan_perubahan_data
    FOR ALL
    USING (current_setting('app.current_user_role', true) = 'opd');

-- Relawan: hanya lihat pengajuan milik sendiri
CREATE POLICY relawan_own_pengajuan ON public.pengajuan_perubahan_data
    FOR SELECT
    USING (
        relawan_id IN (
            SELECT relawan_id FROM public.relawan 
            WHERE user_id = current_setting('app.current_user_id', true)::integer
        )
    );

INSERT INTO relawan (user_id, jenis_kelamin, alamat_ktp, kelurahan)
SELECT 
    u.user_id,
    CASE 
        WHEN u.nama_lengkap ILIKE '%siti%' 
          OR u.nama_lengkap ILIKE '%dewi%' 
          OR u.nama_lengkap ILIKE '%aminah%'
          OR u.nama_lengkap ILIKE '%lestari%'
        THEN 'P'
        ELSE 'L'
    END,
    '-',
    '-'
FROM users u
LEFT JOIN relawan r ON u.user_id = r.user_id
WHERE u.role = 'relawan' 
  AND r.relawan_id IS NULL;