-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_logs
(
    log_id serial NOT NULL,
    user_id integer,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    record_id integer,
    old_value jsonb,
    new_value jsonb,
    ip_address character varying(45) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (log_id)
);

ALTER TABLE IF EXISTS public.audit_logs
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.hotline_settings
(
    id serial NOT NULL,
    telepon character varying(50) COLLATE pg_catalog."default" NOT NULL,
    whatsapp character varying(50) COLLATE pg_catalog."default" NOT NULL,
    jam_layanan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT hotline_settings_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.hotline_settings
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.kader
(
    kader_id serial NOT NULL,
    opd_id integer NOT NULL,
    nama_kader character varying(100) COLLATE pg_catalog."default" NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    sk_id integer,
    CONSTRAINT kader_pkey PRIMARY KEY (kader_id)
);

ALTER TABLE IF EXISTS public.kader
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.opd
(
    opd_id serial NOT NULL,
    nama_opd character varying(255) COLLATE pg_catalog."default" NOT NULL,
    alamat text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    CONSTRAINT opd_pkey PRIMARY KEY (opd_id)
);

ALTER TABLE IF EXISTS public.opd
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pengajuan_perubahan_data
(
    pengajuan_id serial NOT NULL,
    relawan_id integer NOT NULL,
    jenis_perubahan character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_lama jsonb,
    data_baru jsonb NOT NULL,
    status status_pengajuan DEFAULT 'Menunggu Review'::status_pengajuan,
    catatan_relawan text COLLATE pg_catalog."default",
    catatan_verifikator text COLLATE pg_catalog."default",
    tanggal_pengajuan timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    tanggal_verifikasi timestamp with time zone,
    verifikator_id integer,
    CONSTRAINT pengajuan_perubahan_data_pkey PRIMARY KEY (pengajuan_id)
);

ALTER TABLE IF EXISTS public.pengajuan_perubahan_data
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pengelola_opd
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    opd_id integer NOT NULL,
    jabatan character varying(100) COLLATE pg_catalog."default",
    tanggal_mulai date DEFAULT CURRENT_DATE,
    tanggal_selesai date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Aktif'::character varying,
    sk_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pengelola_opd_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.pengelola_opd
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.penugasan_relawan
(
    penugasan_id serial NOT NULL,
    relawan_id integer NOT NULL,
    opd_id integer NOT NULL,
    kader_id integer,
    sk_id integer,
    jabatan character varying(100) COLLATE pg_catalog."default",
    status_keaktifan status_keaktifan DEFAULT 'Aktif'::status_keaktifan,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    penugasan character varying(100) COLLATE pg_catalog."default",
    detail_jabatan character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT penugasan_relawan_pkey PRIMARY KEY (penugasan_id)
);

ALTER TABLE IF EXISTS public.penugasan_relawan
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pic_kader
(
    pic_kader_id serial NOT NULL,
    relawan_id integer NOT NULL,
    kader_id integer NOT NULL,
    tanggal_mulai date DEFAULT CURRENT_DATE,
    tanggal_selesai date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Aktif'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    sk_id integer,
    CONSTRAINT pic_kader_pkey PRIMARY KEY (pic_kader_id)
);

ALTER TABLE IF EXISTS public.pic_kader
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.relawan
(
    relawan_id serial NOT NULL,
    user_id integer NOT NULL,
    jenis_kelamin jenis_kelamin NOT NULL,
    alamat_ktp text COLLATE pg_catalog."default" NOT NULL,
    kelurahan character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT relawan_pkey PRIMARY KEY (relawan_id),
    CONSTRAINT relawan_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.relawan
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.saran_masukan
(
    saran_id serial NOT NULL,
    user_id integer NOT NULL,
    subjek character varying(255) COLLATE pg_catalog."default",
    pesan text COLLATE pg_catalog."default" NOT NULL,
    status status_saran DEFAULT 'Menunggu'::status_saran,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    catatan_admin text COLLATE pg_catalog."default",
    CONSTRAINT saran_masukan_pkey PRIMARY KEY (saran_id)
);

ALTER TABLE IF EXISTS public.saran_masukan
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.surat_keputusan
(
    sk_id serial NOT NULL,
    nomor_sk character varying(100) COLLATE pg_catalog."default" NOT NULL,
    judul_sk character varying(255) COLLATE pg_catalog."default",
    tanggal_terbit date,
    opd_id integer NOT NULL,
    file_path text COLLATE pg_catalog."default" NOT NULL,
    status status_keaktifan DEFAULT 'Aktif'::status_keaktifan,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    batas_aktif date,
    CONSTRAINT surat_keputusan_pkey PRIMARY KEY (sk_id),
    CONSTRAINT surat_keputusan_nomor_sk_key UNIQUE (nomor_sk)
);

ALTER TABLE IF EXISTS public.surat_keputusan
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    nik character varying(16) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role user_role NOT NULL,
    nama_lengkap character varying(255) COLLATE pg_catalog."default" NOT NULL,
    no_hp character varying(15) COLLATE pg_catalog."default",
    foto_profil text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_nik_key UNIQUE (nik)
);

ALTER TABLE IF EXISTS public.users
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.kader
    ADD CONSTRAINT fk_kader_sk FOREIGN KEY (sk_id)
    REFERENCES public.surat_keputusan (sk_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_kader_sk_id
    ON public.kader(sk_id);


ALTER TABLE IF EXISTS public.kader
    ADD CONSTRAINT fk_komunitas_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_komunitas_opd
    ON public.kader(opd_id);


ALTER TABLE IF EXISTS public.pengajuan_perubahan_data
    ADD CONSTRAINT fk_pengajuan_relawan FOREIGN KEY (relawan_id)
    REFERENCES public.relawan (relawan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pengajuan_perubahan_data
    ADD CONSTRAINT fk_pengajuan_verifikator FOREIGN KEY (verifikator_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pengelola_opd
    ADD CONSTRAINT fk_pengelola_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_unique_active_pengelola_per_opd
    ON public.pengelola_opd(opd_id);


ALTER TABLE IF EXISTS public.pengelola_opd
    ADD CONSTRAINT fk_pengelola_sk FOREIGN KEY (sk_id)
    REFERENCES public.surat_keputusan (sk_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_pengelola_opd_sk_id
    ON public.pengelola_opd(sk_id);


ALTER TABLE IF EXISTS public.pengelola_opd
    ADD CONSTRAINT fk_pengelola_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_komunitas FOREIGN KEY (kader_id)
    REFERENCES public.kader (kader_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_penugasan_komunitas
    ON public.penugasan_relawan(kader_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_penugasan_opd
    ON public.penugasan_relawan(opd_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_relawan FOREIGN KEY (relawan_id)
    REFERENCES public.relawan (relawan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_penugasan_relawan
    ON public.penugasan_relawan(relawan_id);


ALTER TABLE IF EXISTS public.penugasan_relawan
    ADD CONSTRAINT fk_penugasan_sk FOREIGN KEY (sk_id)
    REFERENCES public.surat_keputusan (sk_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pic_kader
    ADD CONSTRAINT fk_pic_kader FOREIGN KEY (kader_id)
    REFERENCES public.kader (kader_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS unique_active_pic_per_kader
    ON public.pic_kader(kader_id);


ALTER TABLE IF EXISTS public.pic_kader
    ADD CONSTRAINT fk_pic_kader_sk FOREIGN KEY (sk_id)
    REFERENCES public.surat_keputusan (sk_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_pic_kader_sk_id
    ON public.pic_kader(sk_id);


ALTER TABLE IF EXISTS public.pic_kader
    ADD CONSTRAINT fk_pic_relawan FOREIGN KEY (relawan_id)
    REFERENCES public.relawan (relawan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.relawan
    ADD CONSTRAINT fk_relawan_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS relawan_user_id_key
    ON public.relawan(user_id);


ALTER TABLE IF EXISTS public.saran_masukan
    ADD CONSTRAINT fk_saran_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.surat_keputusan
    ADD CONSTRAINT fk_sk_opd FOREIGN KEY (opd_id)
    REFERENCES public.opd (opd_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;